#!/bin/bash

set -e

# Modules
for ext in reitit-core reitit-ring reitit-spec reitit-schema reitit-swagger reitit-swagger-ui reitit-frontend reitit-re-frame reitit; do
  cd modules/$ext; lein "$@"; cd ../..;
done
